 CREATE TABLE CONTACTS (
  UUID uuid PRIMARY KEY,
  FIRST_NAME VARCHAR (50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  HOME_PHONE VARCHAR(30),
  WORK_PHONE VARCHAR(30),
  MOBILE_PHONE VARCHAR(30)
  );